<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transaction Receipt #{{ $transaction->id }}</title>
    <link rel="stylesheet" href="{{ public_path('css/pdf.css') }}">
</head>
<body>
    <div class="header">
        <h1>Book Transaction Receipt</h1>
        <p>Library Management System</p>
        <p>Generated on: {{ now()->format('M d, Y h:i A') }}</p>
    </div>

    <div class="two-columns">
        <div class="column">
            <div class="receipt-info">
                <h2>Transaction Details</h2>
                <div class="info-row">
                    <span class="info-label">Transaction ID:</span>
                    <span class="info-value"><strong>#{{ $transaction->id }}</strong></span>
                </div>
                <div class="info-row">
                    <span class="info-label">Status:</span>
                    <span class="info-value">
                        <span class="status-badge status-{{ strtolower($transaction->status) }}">
                            {{ ucfirst($transaction->status) }}
                        </span>
                    </span>
                </div>
                <div class="info-row">
                    <span class="info-label">Borrow Date:</span>
                    <span class="info-value">{{ $transaction->borrowed_at ? \Carbon\Carbon::parse($transaction->borrowed_at)->format('M d, Y') : 'N/A' }}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Due Date:</span>
                    <span class="info-value">{{ $transaction->due_date ? \Carbon\Carbon::parse($transaction->due_date)->format('M d, Y') : 'N/A' }}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Return Date:</span>
                    <span class="info-value">{{ $transaction->returned_at ? \Carbon\Carbon::parse($transaction->returned_at)->format('M d, Y') : 'Not returned' }}</span>
                </div>
            </div>

            <div class="receipt-info">
                <h2>User Information</h2>
                <div class="info-row">
                    <span class="info-label">Name:</span>
                    <span class="info-value">{{ optional($transaction->user)->firstName }} {{ optional($transaction->user)->lastName }}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Email:</span>
                    <span class="info-value">{{ optional($transaction->user)->email ?? 'N/A' }}</span>
                </div>
            </div>
        </div>

        <div class="column">
            <div class="receipt-info">
                <h2>Book Information</h2>
                <div class="book-info">
                    <div class="info-row">
                        <span class="info-label">Title:</span>
                        <span class="info-value"><strong>{{ optional($transaction->book)->title ?? 'N/A' }}</strong></span>
                    </div>
                    <div class="info-row">
                        <span class="info-label">Author:</span>
                        <span class="info-value">{{ optional($transaction->book)->author ?? 'N/A' }}</span>
                    </div>
                    <div class="info-row">
                        <span class="info-label">ISBN:</span>
                        <span class="info-value">{{ optional($transaction->book)->isbn ?? 'N/A' }}</span>
                    </div>
                    <div class="info-row">
                        <span class="info-label">Category:</span>
                        <span class="info-value">{{ optional($transaction->book)->category ?? 'N/A' }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fee-box">
        <div class="label">Transaction Fee</div>
        <div class="amount">₱{{ number_format($transaction->fee ?? 0, 2) }}</div>
        @if($transaction->fee > 0)
            <p style="margin: 5px 0 0 0; font-size: 10px; color: #856404;">
                @if($transaction->status === 'overdue')
                    (Overdue charges apply)
                @elseif($transaction->status === 'returned')
                    (Fee paid)
                @endif
            </p>
        @else
            <p style="margin: 5px 0 0 0; font-size: 10px; color: #856404;">No fees charged</p>
        @endif
    </div>

    <div class="footer">
        <p><strong>Library Management System</strong></p>
        <p>This is an official receipt generated by the system.</p>
        <p>For any inquiries, please contact the library administration.</p>
    </div>
</body>
</html>
